name: Flutter CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # replace with your Flutter version

      - name: Install dependencies
        run: flutter pub get
        working-directory: ems-notes-app/app_ws

      - name: Run analyzer (lint)
        run: flutter analyze
        working-directory: ems-notes-app/app_ws

      - name: Run tests
        run: flutter test
        working-directory: ems-notes-app/app_ws
